export const data = {
  messages: [
    "Oi, vocês têm tênis da Nike tamanho 42?",
    "Qual o prazo de entrega para São Paulo?",
    "Tem desconto para pagamento à vista?",
    "Vocês parcelam no Pix?",
    "Qual o valor do frete para o Rio de Janeiro?",
    "Esse modelo de jaqueta tem outras cores?",
    "Bom dia! Como faço para trocar um produto?",
    "A blusa P veste bem em quem tem 1,65m?",
    "O relógio vem com garantia?",
    "Esse perfume é original?",
    "Oi, posso retirar na loja?",
    "Quais formas de pagamento vocês aceitam?",
    "Tem promoção hoje?",
    "Gostaria de comprar 3 unidades, tem desconto?",
    "Esse produto está disponível para envio imediato?",
    "Vocês fazem entrega no mesmo dia?",
    "A mochila cabe um notebook de 15 polegadas?",
    "Tem cupom de desconto para primeira compra?",
    "Qual a validade desse produto?",
    "Esse modelo de sandália é confortável?",
    "Posso pagar metade agora e metade na entrega?",
    "Vocês têm loja física?",
    "A camiseta é de algodão?",
    "O celular vem desbloqueado para todas operadoras?",
    "Posso personalizar esse produto?",
    "Vocês vendem no atacado?",
    "O brinco é antialérgico?",
    "Consigo rastrear meu pedido?",
    "O tapete pode ser lavado na máquina?",
    "Esse shampoo é indicado para cabelos cacheados?",
    "Tem como enviar foto real do produto?",
    "Quanto tempo demora para postar nos Correios?",
    "Vocês têm suporte pós-venda?",
    "A bolsa tem divisórias internas?",
    "Esse sofá desmonta para transporte?",
    "Esse fone é Bluetooth?",
    "Vocês aceitam vale-alimentação?",
    "Esse jogo de panelas serve para fogão de indução?",
    "O kit vem com todos os acessórios da foto?",
    "A calça jeans tem elastano?",
    "Consigo retirar amanhã cedo?",
    "Vocês têm garantia estendida?",
    "Qual a política de devolução?",
    "Posso mudar a cor depois de fazer o pedido?",
    "Esse tênis é indicado para corrida?",
    "O vestido tem forro?",
    "A sandália tem salto confortável?",
    "Vocês fazem envio internacional?",
    "O colchão é ortopédico?",
    "Tem como parcelar no boleto?",
    "Qual o código de rastreio do meu pedido?",
    "A cadeira suporta até quantos quilos?",
    "Posso pagar com dois cartões diferentes?",
    "O produto vem com manual de instruções?",
    "Esse smartwatch mede pressão arterial?",
    "A maquiagem é testada em animais?",
    "Esse travesseiro é antialérgico?",
    "Os brincos são folheados a ouro?",
    "O casaco é corta-vento?",
    "O perfume tem boa fixação?",
    "A TV vem com suporte de parede?",
    "O berço vira cama?",
    "Essa panela pode ir ao forno?",
    "A camisa amassa fácil?",
    "O ferro de passar é bivolt?",
    "O celular tem garantia nacional?",
    "A bicicleta vem montada?",
    "Tem esse tênis no número 39?",
    "Qual o melhor fone para academia?",
    "Tem como pagar com PayPal?",
    "O relógio é à prova d'água?",
    "Qual o tamanho ideal para 1,80m de altura?",
    "Vocês enviam por transportadora?",
    "Esse teclado é mecânico?",
    "Tem como enviar sem a caixa?",
    "Esse óculos tem proteção UV?",
    "O tênis é impermeável?",
    "A bateria dura quantas horas?",
    "O controle é compatível com Xbox?",
    "Posso pagar na entrega?",
    "Qual o valor do frete para Curitiba?",
    "Esse sofá tem almofadas removíveis?",
    "Esse tapete solta pelo?",
    "O moletom encolhe na lavagem?",
    "A TV tem garantia de fábrica?",
    "Essa câmera filma em 4K?",
    "O projetor tem entrada HDMI?",
    "Esse notebook é bom para jogos?",
    "O celular vem com película?",
    "Esse mouse é sem fio?",
    "O liquidificador faz suco sem coar?",
    "Essa bota é resistente à água?",
    "Tem garantia contra defeitos de fabricação?",
    "Essa tinta sai fácil da roupa?",
    "Esse fone tem cancelamento de ruído?",
    "O cobertor é de microfibra?",
    "A sanduicheira é antiaderente?",
    "Esse ar-condicionado é silencioso?",
    "Esse tênis serve para caminhada?",
    "Essa chapinha esquenta rápido?",
    "O ventilador faz muito barulho?",
    "Esse smartwatch sincroniza com iPhone?",
    "A cafeteira é compatível com cápsulas?",
    "Tem como gravar nome no produto?",
    "Esse secador de cabelo tem difusor?",
    "O perfume é importado?",
    "Esse carregador é turbo?",
    "O colchão tem densidade D33?",
    "A mesa é desmontável?",
    "O aspirador de pó é sem fio?",
    "Esse fogão tem acendimento automático?",
    "O chuveiro tem resistência blindada?",
    "Esse ferro a vapor é potente?",
    "A máquina de lavar é 220V?",
    "O edredom é dupla face?",
    "O micro-ondas tem grill?",
    "Esse banco suporta até 150kg?",
    "O relógio vem com pulseira extra?",
    "O tênis é antiderrapante?",
    "O carregador vem com cabo incluso?",
    "A bolsa tem zíper interno?",
    "Esse ventilador tem controle remoto?",
    "O teclado tem iluminação RGB?",
    "O drone tem câmera?",
    "O celular suporta 5G?",
    "Esse shampoo ajuda no crescimento capilar?",
    "O massageador tem regulagem de intensidade?",
    "Esse copo térmico mantém a temperatura por quanto tempo?",
    "A geladeira tem freezer separado?",
    "O forno tem timer?",
    "O patinete elétrico tem boa autonomia?",
    "O roteador tem boa cobertura?",
    "A TV tem entrada para pendrive?",
    "O colchão é de molas ensacadas?",
    "O carregador sem fio funciona com iPhone?",
    "O suporte de celular é ajustável?",
    "A caixa de som tem Bluetooth?",
    "A jaqueta é resistente ao frio intenso?",
    "O cabo HDMI tem quantos metros?",
    "Esse conjunto de talheres é inox?",
    "A garrafa térmica mantém a temperatura por quanto tempo?",
    "O tênis tem amortecimento?",
    "O aquecedor de ambiente é bivolt?",
    "O tablet tem suporte para caneta?",
    "O ar-condicionado tem filtro antiácaro?",
    "Essa base para notebook tem cooler?",
    "O banco para moto é confortável?",
    "A câmera de segurança grava no escuro?",
    "O colchão inflável vem com bomba?",
    "A bateria desse smartwatch é recarregável?",
    "O tapete de yoga é antiderrapante?",
    "Essa luminária tem ajuste de intensidade?",
    "O fone de ouvido tem microfone?",
    "Essa bolsa é impermeável?",
    "O aquecedor é silencioso?",
    "O carrinho de bebê reclina?",
    "O tablet tem entrada para chip?",
    "A bicicleta tem marcha?",
    "Esse perfume é unissex?",
    "O aspirador robô tem sensor de obstáculos?",
    "O cooktop é fácil de instalar?",
    "O microfone tem boa captação?",
    "A bateria do drone dura quanto tempo?",
    "Esse smartwatch tem GPS?",
    "Esse conjunto de panelas pode ir ao lava-louças?",
    "O tênis tem palmilha macia?",
    "Essa mochila tem compartimento para laptop?",
    "A caixa de som é à prova d água?",
  ],
};
