import {
  Activity,
  AlertTriangle,
  ArrowRight,
  Bot,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Clock,
  Command,
  CreditCard,
  Database,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  MessageSquare,
  MessageSquareMore,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  QrCode,
  ScrollText,
  Settings,
  Smartphone,
  SunMedium,
  Trash,
  Twitter,
  User,
  User2Icon,
  Users,
  UserX2Icon,
  X,
  Zap,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  reactive: MessageSquareMore,
  trigger: Zap,
  logs: ScrollText,
  contacts: Users,
  database: Database,
  whatsapp: Smartphone,
  qrcode: QrCode,
  bot: Bot,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  connection: Activity,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  clock: Clock,
  message: MessageSquare,
};
